### ISSUE TITLE
duplicate routes

### ISSUE THREAD

**Issue by timoxley** [yoshuawuyts/wayfarer#13]
currently handlers for duplicate routes simply clobber each other.

Should probably forbid this or notify user if clobbering a route or allow multiple handlers for the same route.

**Comment by yoshuawuyts** [comment]
Not sure having duplicate handlers makes sense for views. Leaning towards using `throw` here.

**Comment by timoxley** [comment]
You could be right though perhaps it does make sense, could allow different handlers across different concerns… perhaps they attach from different sub-modules for example.

**Comment by yoshuawuyts** [comment]
Ah right; well guess there's no harm in adding multiple handlers if you think there's a use case for it (: Maybe add a `{multi: true}` opt per handler to signal this is possible, or would that complicate the api too much?

**Comment by yoshuawuyts** [comment]
I think it makes sense to just allow multiple handlers per route, no need to enable flags / pass settings imo.

**Comment by yoshuawuyts** [comment]
released as `wayfarer@4.1.0`
