### ISSUE TITLE
remove .match() ?

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/wayfarer#17]
I've been thinking about this lately, and I'm not sure `.match()` should live in `wayfarer`. I'm having a hard time thinking of a use case where `.match()` should be called from wayfarer, instead of just consuming [`routington`](https://github.com/pillarjs/routington) directly. It also complicates nesting routes (see https://github.com/yoshuawuyts/wayfarer/pull/14#issuecomment-111766696).

I'm wondering if there are reasons why it wouldn't make sense to use `routington` directly. If there's a +1 for removing `.match()`, it could become part of the next `semver-major`.

cc/ @shama

p.s. I still wish `base-router` is built on top of `wayfarer`, but if it needs low level operations `routington` might be the more natural fit. Just checking if that is the case.

**Comment by shama** [comment]
My use case for it is to know when a route has matched without calling the callback. To give the user the option to handle it. Whether sending a 404 on the server or UI on the client or defaulting to some other asset.

If `.match()` isn't a good _match_ (hehe) for `wayfarer`, I'm okay just using `routington` directly instead.

**Comment by yoshuawuyts** [comment]
Lolol. I created a PR for `routington` on `base-router`. It seems to fill the use case pretty well (':

**Comment by yoshuawuyts** [comment]
published as `wayfarer@4.0.0`
