### ISSUE TITLE
add a walk function

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/wayfarer#43]
Would be nice to have a `walk.js` file which exposes one function to walk and edit the trie.

Related issues:
- https://github.com/yoshuawuyts/sheet-router/issues/30
- https://github.com/yoshuawuyts/server-router/issues/10

__edit:__ wording

**Comment by mcollina** [comment]
Also edit, meaning that we can add a function wrapper if we want to.

**Comment by yoshuawuyts** [comment]
Aye yeah, for sure!
