### ISSUE TITLE
Activity ❓❓❓

### ISSUE THREAD

**Issue by snuggs** [yoshuawuyts/wayfarer#49]
@yoshuawuyts is there any activity on this? Are we accepting contributions here? I've attempted to contribute to page.js but it's hella stagnant. Having problems using this tool with es6 imports via http://rollupjs.org . Looking to make a contribution. Thanks in advance!

**Comment by mcollina** [comment]
Hey @snuggs. You can get your answer from https://github.com/yoshuawuyts/wayfarer/commits/master and npm as well. The last release was done 7 days ago. Feel free to send your PR!

**Comment by snuggs** [comment]
Thanks @mcollina! Also, Is there any reason wayfarer doesn't subscribe to the window.history API? This is one feature I think would be a great addition. What say you? 

https://developer.mozilla.org/en-US/docs/Web/API/History_API#Example_of_pushState()_method

**Comment by yoshuawuyts** [comment]
wayfarer has no opinions on where it's used. If you're looking for a
specialized frontend router that handles the history API
https://github.com/yoshuawuyts/sheet-router/blob/master/history.js might be
closer to what you're looking for ✨

**Comment by snuggs** [comment]
oh i see @yoshuawuyts. Only thing about sheet router is the API is a bit funky. Wayfarer's is far sexier. ;-)

**Comment by snuggs** [comment]
Thanks for the input gentlemen. @yoshuawuyts @mcollina. Closing issue.
