### ISSUE TITLE
trie.nodes is undefined on /watch/:anything

### ISSUE THREAD

**Issue by jongacnik** [yoshuawuyts/wayfarer#58]
Ran into an issue which seems to live in bug land. If the word `watch` is used as the base route before a partial, the router will break on a `TypeError: trie.nodes is undefined`, but **only** in Firefox (52.0.2):

```js
var wayfarer = require('wayfarer')
var router = wayfarer()
// crashes app in Firefox
router.on('/watch/:anything', (params) => console.log('nope'))
```

If the base route is anything other than watch, everything is fine:

```js
// works in Firefox!
router.on('/watchh/:anything', (params) => console.log('yep'))
```

Haven't yet looked into what might be causing this, but can when I have a moment. Here is a running version of the example which breaks in Firefox:

Demo: https://wayfarer-weird.glitch.me/
Code: https://glitch.com/edit/#!/wayfarer-weird?path=public/client.js

**Comment by yoshuawuyts** [comment]
Hahaha, woah - would you mind filing this on https://webcompat.com/ and
linking back here? I regularly hang out with web compat engineers and this
seems like a fun one to debug when we're hanging out haha. Thanks!

**Comment by yoshuawuyts** [comment]
(This is such an odd, specific bug - very curious - thanks heaps for
finding this!)

**Comment by yoshuawuyts** [comment]
Cool, so as per https://github.com/webcompat/web-bugs/issues/5699#issuecomment-294504585 we should probably do a `.hasOwnProperty` check when referencing the object rather than straight up accessing it

**Comment by yoshuawuyts** [comment]
`v6.5.1`
